apiVersion: v1
kind: ConfigMap
metadata:
  name: nitter-nginx-conf
data:
  nginx.conf: |-
    user nginx;
    worker_processes 1;
    events {
      worker_connections 10240;
    }
    http {
      server {
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
        add_header Content-Security-Policy "default-src 'none'; script-src 'self' 'unsafe-inline'; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'; media-src 'self' blob:; worker-src 'self' blob:; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; connect-src 'self' https://*.twimg.com; manifest-src 'self'";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;
        add_header X-XSS-Protection "1; mode=block";
        location / {
            proxy_pass http://127.0.0.1:8000;
        }
        location = /robots.txt {
          add_header Content-Type text/plain;
          return 200 "User-agent: *\nDisallow: /\n";
        }
      }
    }
